/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Meu_segundo_projeto_Java;

//HErança 
//Poliformismo
public class App {

    

    public static void main(String[] args) {
    	Equipe equipeceuazul= new Equipe ();
    	equipeceuazul.v1 = new Avião (new MotorAviãoSuper());
    	equipeceuazul.v2 = new Avião(new MotorAviãoSuper());
    	equipeceuazul.p1 = new PilotoAvião ("Schumaquer", 30);
    	equipeceuazul.p2 = new PilotoAvião("Rubinho",30);
    	equipeceuazul.mecanicos.add(new Mecanico());
    	equipeceuazul.mecanicos.add(new Mecanico());
    	equipeceuazul.mecanicos.add(new Mecanico());
    	equipeceuazul.mecanicos.add(new Mecanico());
    	equipeceuazul.mecanicos.add(new Mecanico());
    	
    	equipeceuazul.v1.Acelerar(10);
    	System.out.println(equipeceuazul.v1.Acelerar(5));
    
    	
    }
 
}
